/**
 * CÂMARA DE SÍNTESE
 * Mantém os oito slots e traduz mouse, toque e teclado para as mesmas regras.
 * O DOM é apenas uma representação: slots bloqueados nunca entram no cálculo.
 */
class FusionGridManager {
    constructor(session=null){this.session=session;this.totalSlots=8;this.unlockedSlots=4;this.slots=new Array(8).fill(null);this.selectedSlotIndex=null;this.draggedIndex=null;this.container=document.getElementById('fusion-slots-container');this.abortController=new AbortController();this.touchGhost=null;if(this.container){this.initDOM();this.initEvents();}}
    get manager(){return this.session?.missions||window.missionManager;} get engine(){return this.session?.engine||window.gameEngine;}
    isUnlocked(i){return Number.isInteger(i)&&i>=0&&i<this.unlockedSlots;} countActiveAtoms(){return this.slots.slice(0,this.unlockedSlots).filter(Boolean).length;}
    initDOM(){this.container.textContent='';for(let i=0;i<8;i++){const w=document.createElement('div'),b=document.createElement('button');w.className='slot-wrap';b.type='button';b.className='atom-slot';b.dataset.slotIndex=i;w.append(b);this.container.append(w);}this.renderSlots();}
    initEvents(){const o={signal:this.abortController.signal};this.container.addEventListener('click',e=>{const sell=e.target.closest('.btn-sell-atom');if(sell)return this.sellAtom(Number(sell.dataset.slotIndex));const s=e.target.closest('.atom-slot');if(s)this.activateSlot(Number(s.dataset.slotIndex));},o);this.container.addEventListener('dragstart',e=>{const x=e.target.closest('.atom-item');if(x){this.draggedIndex=Number(x.dataset.slotIndex);e.dataTransfer?.setData('text/plain',String(this.draggedIndex));}},o);this.container.addEventListener('dragover',e=>{if(e.target.closest('.atom-slot:not(:disabled)'))e.preventDefault();},o);this.container.addEventListener('drop',e=>{e.preventDefault();const s=e.target.closest('.atom-slot');if(s&&this.draggedIndex!==null)this.handleDropLogic(this.draggedIndex,Number(s.dataset.slotIndex));this.cleanupDrag();},o);this.container.addEventListener('dragend',()=>this.cleanupDrag(),o);this.bindTouchEvents(o);}
    announce(m){this.manager?.showToast(m);const s=document.getElementById('game-status');if(s)s.textContent=m;}
    activateSlot(i){if(!this.isUnlocked(i))return this.announce(`Slot ${i+1} bloqueado.`);if(this.selectedSlotIndex===null){if(!this.slots[i])return this.announce(`Slot ${i+1} vazio.`);this.selectedSlotIndex=i;}else if(this.selectedSlotIndex===i)this.selectedSlotIndex=null;else{const from=this.selectedSlotIndex;this.selectedSlotIndex=null;this.handleDropLogic(from,i);}this.renderSlots(i);}
    buyNextSlot(){if(this.unlockedSlots>=8)return false;const required=this.unlockedSlots-2,cost=AtomicRules.slotCost(this.unlockedSlots+1,this.engine?.prestigeLevel||0);if(!this.engine||this.manager?.fusionLevel<required||this.engine.coins<cost){this.announce(`Slot ${this.unlockedSlots+1}: requer acelerador N${required} e ${cost} moedas.`);return false;}this.engine.coins-=cost;this.unlockedSlots++;this.manager?.recordSlotPurchase?.();this.renderSlots();this.engine.markUiDirty?.();SaveManager.save();return true;}
    buyAndSpawnElement(z,cost){const e=this.engine,i=this.slots.slice(0,this.unlockedSlots).findIndex(x=>x===null);if(!e||e.coins<cost||i<0||!ATOM_REGISTRY[z]){this.announce('Sem espaço ativo ou saldo suficiente.');return false;}e.coins-=cost;this.addAtomToSlot(i,z,'purchase');e.markUiDirty?.();return true;}
    addAtomToSlot(i,z,source='injection'){if(!this.isUnlocked(i)||this.slots[i]||!ATOM_REGISTRY[z])return false;this.slots[i]={protons:z,uuid:AtomicRules.safeUuid()};this.renderSlots(i);this.syncWithAccelerator();if(source!=='fusion')this.manager?.recordAtomAdded?.(z);SaveManager.updateEmergencyButtonState();return true;}
    sellAtom(i){if(!this.isUnlocked(i)||!this.slots[i]||!this.engine)return false;const a=this.slots[i],mass=Number(ATOM_REGISTRY[a.protons].massValue||ATOM_REGISTRY[a.protons].mass)||a.protons;this.engine.coins+=Math.max(1,Math.floor(mass*(this.engine.prestigeLevel+1)*.5));this.slots[i]=null;this.manager?.recordAtomSold?.();this.renderSlots(i);this.syncWithAccelerator();SaveManager.save();return true;}
    handleDropLogic(a,b){if(!this.isUnlocked(a)||!this.isUnlocked(b)||!this.slots[a])return this.announce('Ação bloqueada para este slot.');if(!this.slots[b])return this.swapSlots(a,b);const l=this.slots[a].protons,r=this.slots[b].protons,rule=AtomicRules.canSynthesize(l,r,{acceleratorLevel:this.manager?.fusionLevel||1,cryoLevel:this.manager?.postIronModules?.cryo||0,toroidalLevel:this.manager?.postIronModules?.toroidal||0});if(!rule.ok)return this.announce(rule.reason);this.executeFusionSuccess(a,b,l,r,rule.resultZ);}
    executeFusionSuccess(a,b,l,r,z){this.slots[a]=null;this.slots[b]={protons:z,uuid:AtomicRules.safeUuid()};this.renderSlots(b);const resultSlot=this.container.querySelector(`[data-slot-index="${b}"]`);resultSlot?.classList.add('fusion-pulse');this.syncWithAccelerator();QuantumAudio?.playFusionSuccess?.();this.manager?.recordFusion?.(z,l,r,resultSlot);SaveManager.save();}
    swapSlots(a,b){if(!this.isUnlocked(a)||!this.isUnlocked(b))return false;[this.slots[a],this.slots[b]]=[this.slots[b],this.slots[a]];this.renderSlots(b);this.syncWithAccelerator();return true;}
    renderSlots(focus=null){this.container.querySelectorAll('.slot-wrap').forEach((wrap,i)=>{const old=wrap.querySelector('.btn-sell-atom');old?.remove();const s=wrap.querySelector('.atom-slot'),unlocked=this.isUnlocked(i),a=this.slots[i];s.textContent='';s.disabled=!unlocked;s.className=`atom-slot${a?' has-atom':''}${i===this.selectedSlotIndex?' selected-slot':''}${unlocked?'':' locked-slot'}`;s.setAttribute('aria-pressed',String(i===this.selectedSlotIndex));if(!unlocked){s.textContent='🔒';s.setAttribute('aria-label',`Slot ${i+1}, bloqueado`);return;}if(!a){s.innerHTML='<span class="slot-empty" aria-hidden="true">+</span>';s.setAttribute('aria-label',`Slot ${i+1}, vazio`);return;}const d=ATOM_REGISTRY[a.protons],item=document.createElement('span'),img=document.createElement('img'),badge=document.createElement('span');item.className='atom-item';item.draggable=true;item.dataset.slotIndex=i;img.className='atom-sprite';img.src=atomTextures.getTexture(d).src;img.alt='';img.onerror=()=>{img.onerror=null;img.src=atomTextures.generateFallback(d);};badge.className='atom-badge';badge.textContent=`${d.symbol} — Z=${d.protons}`;item.append(img,badge);s.append(item);s.setAttribute('aria-label',`Slot ${i+1}, ${d.namePt}, Z igual a ${d.protons}. Selecione para mover ou fundir.`);const sell=document.createElement('button');sell.type='button';sell.className='btn-sell-atom';sell.dataset.slotIndex=i;sell.textContent='✕';sell.setAttribute('aria-label',`Vender ${d.namePt} do slot ${i+1}`);wrap.append(sell);});if(focus!==null)this.container.querySelector(`[data-slot-index="${focus}"]`)?.focus();this.updateSlotPurchaseUI();}
    updateSlotPurchaseUI(){const b=document.getElementById('btn-buy-slot');if(!b)return;b.classList.remove('slot-level-locked');if(this.unlockedSlots>=8){b.textContent='8/8 SLOTS';b.disabled=true;b.title='Todos os oito slots estão liberados.';b.setAttribute('aria-label','Todos os oito slots da Câmara de Síntese estão liberados.');return;}const next=this.unlockedSlots+1,lv=this.unlockedSlots-2,c=AtomicRules.slotCost(next,this.engine?.prestigeLevel||0),current=this.manager?.fusionLevel||1;if(current<lv){b.textContent=`REQUER NÍVEL ${lv}`;b.disabled=true;b.classList.add('slot-level-locked');b.title=`O slot ${next} exige Anel de Síntese Nível ${lv}.`;b.setAttribute('aria-label',`Slot ${next} bloqueado. Requer Anel de Síntese Nível ${lv}. Nível atual ${current}.`);return;}b.textContent=`LIBERAR SLOT ${next} · ${c}`;b.disabled=(this.engine?.coins||0)<c;b.title=`Liberar o slot ${next} por ${c} moedas.`;b.setAttribute('aria-label',`${b.disabled?'Moedas insuficientes. ':''}Liberar slot ${next} por ${c} moedas.`);}
    syncWithAccelerator(){this.engine?.syncParticles(this.slots.slice(0,this.unlockedSlots).filter(Boolean));}
    cleanupDrag(){this.draggedIndex=null;this.touchGhost?.remove();this.touchGhost=null;}
    bindTouchEvents(o){let origin=null;this.container.addEventListener('touchstart',e=>{const x=e.target.closest('.atom-item');if(!x)return;origin=Number(x.dataset.slotIndex);this.touchGhost=x.cloneNode(true);this.touchGhost.className+=' atom-ghost';document.body.append(this.touchGhost);},{...o,passive:true});this.container.addEventListener('touchend',e=>{const t=e.changedTouches[0],s=document.elementFromPoint(t.clientX,t.clientY)?.closest('.atom-slot');if(s&&origin!==null)this.handleDropLogic(origin,Number(s.dataset.slotIndex));origin=null;this.cleanupDrag();},o);this.container.addEventListener('touchcancel',()=>{origin=null;this.cleanupDrag();},o);}
    destroy(){this.abortController.abort();this.cleanupDrag();this.slots.fill(null);this.engine?.syncParticles([]);}
}
