/**
 * CAMADA DE INTEGRIDADE
 * Reúne save validado, migrações, progresso vitalício, módulos pós-ferro e o
 * ciclo de vida compartilhado. Ela envolve módulos antigos sem duplicar suas
 * regras visuais e é a fonte autoritativa da persistência da Build 1.
 */
(function(){
    'use strict';
    // O save v6 preserva tanto descobertas químicas quanto fragmentos históricos.
    const KEY='atomic_idle_save_v6',V5='atomic_idle_save_v5',V4='atomic_idle_save_v4',V3='atomic_idle_save_v3',LEGACY='atomic_fusion_local_save_v2',BACKUP='atomic_idle_corrupt_backup';
    const storage={available:true,get(k){try{return localStorage.getItem(k);}catch(e){this.fail(e);return null;}},set(k,v){try{localStorage.setItem(k,v);return true;}catch(e){this.fail(e);return false;}},remove(k){try{localStorage.removeItem(k);return true;}catch(e){this.fail(e);return false;}},fail(e){this.available=false;console.warn('[Atomic Idle][storage]',e);queueMicrotask(()=>{const n=document.getElementById('storage-warning');if(n){n.textContent='Armazenamento indisponível: esta sessão funciona, mas o progresso não será salvo.';n.classList.remove('hidden');}});}};
    function migrateLegacy(d){if(!d||typeof d!=='object')return null;const level=Math.max(1,Math.min(14,Math.trunc(d.fusionLevel||1))),unlocked=Math.min(AtomicRules.unlockedForLevel(level),4),known=[1,...(Array.isArray(d.synthesizedZ)?d.synthesizedZ:[])];return{saveVersion:5,revision:0,savedAt:Number(d.timestamp)||Date.now(),coins:Math.max(0,Number(d.coins)||0),photons:Math.max(0,Number(d.photons)||0),prestigeLevel:Math.max(0,Math.trunc(d.prestigeLevel||0)),playerLevel:Math.max(1,Math.min(50,Math.trunc(d.playerLevel||1))),currentMissionIndex:Math.max(0,Math.min(49,Math.trunc(d.currentMissionIndex||0))),fusionLevel:level,unlockedSlots:unlocked,slots:Array.from({length:8},(_,i)=>i<unlocked&&ATOM_REGISTRY[d.slots?.[i]?.protons]?{protons:d.slots[i].protons}:null),modules:{cryo:0,toroidal:0},round:{detections:0,fusions:Math.max(0,Math.trunc(d.totalFusions||0)),detectedCoins:0,slotsBought:0,modulesBought:0},synthesizedZ:[],discoveredZLifetime:[...new Set(known.filter(z=>Number.isInteger(z)&&z>=1&&z<=118))],hydrogenCardPresented:false,reactionCounts:{},missionState:'active',replacementMission:null,speedBonus:Math.max(0,Math.min(1,Number(d.speedBonus)||0),0),detectorsCount:Math.max(1,Math.min(10,Math.trunc(d.detectorsCount||1))),currentInjectorZ:Math.max(1,Math.min(118,Math.trunc(d.currentInjectorZ||1))),buffExpiresAt:{collider:0,cryo:0,condenser:0},offlineHoursLevel:Math.max(0,Math.min(10,Math.trunc(d.offlineHoursLevel||0))),quantumLuckLevel:Math.max(0,Math.min(10,Math.trunc(d.quantumLuckLevel||0)))};}
    /** Monta uma fotografia completa e validável do estado persistente. */
    function payload(){const s=window.atomicSession,e=s.engine,g=s.grid,m=s.missions;return{saveVersion:6,revision:++s.revision,savedAt:Date.now(),coins:e.coins,photons:e.photons,prestigeLevel:e.prestigeLevel,playerLevel:m.playerLevel,currentMissionIndex:m.currentMissionIndex,fusionLevel:m.fusionLevel,unlockedSlots:g.unlockedSlots,slots:g.slots.map(a=>a?{protons:a.protons}:null),modules:{...m.postIronModules},round:{...m.roundCounters},synthesizedZ:[...m.synthesizedElements],discoveredZLifetime:[...m.discoveredElementsLifetime].sort((a,b)=>a-b),hydrogenCardPresented:Boolean(m.hydrogenCardPresented),historyUnlockedIds:[...(m.historyUnlockedIds||[])],historySeenIds:[...(m.historySeenIds||[])],pendingHistoryFragmentId:m.pendingHistoryFragmentId||null,reactionCounts:{...m.reactionCounts},missionState:m.missionState,replacementMission:m.replacementMission,prestigeCalibrationStart:m.prestigeCalibrationStart||0,speedBonus:e.speedBonus,detectorsCount:e.detectors.length,currentInjectorZ:m.currentInjectorZ,buffExpiresAt:{...e.buffExpiresAt},offlineHoursLevel:m.offlineHoursLevel||0,quantumLuckLevel:m.quantumLuckLevel||0};}
    /** Aplica o save somente depois que todas as suas estruturas foram validadas. */
    function apply(d){const s=window.atomicSession,e=s.engine,g=s.grid,m=s.missions;e.coins=d.coins;e.photons=d.photons;e.prestigeLevel=d.prestigeLevel;e.speedBonus=d.speedBonus;e.buffExpiresAt={...d.buffExpiresAt};e.detectors=[];for(let i=0;i<d.detectorsCount;i++)e.detectors.push({angle:i*Math.PI*2/d.detectorsCount,pulseTimer:0,label:`DET-${String(i+1).padStart(2,'0')}`});m.playerLevel=d.playerLevel;m.currentMissionIndex=d.currentMissionIndex;m.fusionLevel=d.fusionLevel;m.currentInjectorZ=d.currentInjectorZ;m.postIronModules={...d.modules};m.roundCounters={...d.round};m.synthesizedElements=new Set(d.synthesizedZ);m.discoveredElementsLifetime=new Set(d.discoveredZLifetime);m.hydrogenCardPresented=d.hydrogenCardPresented;m.historyUnlockedIds=new Set(d.historyUnlockedIds);m.historySeenIds=new Set(d.historySeenIds);m.pendingHistoryFragmentId=d.pendingHistoryFragmentId;m.reactionCounts={...d.reactionCounts};m.missionState=d.missionState||'active';m.replacementMission=d.replacementMission||null;m.dynamicSubstitute=d.replacementMission?{...d.replacementMission}:null;m.prestigeCalibrationStart=Math.max(0,Number(d.prestigeCalibrationStart)||0);m.offlineHoursLevel=d.offlineHoursLevel;m.quantumLuckLevel=d.quantumLuckLevel;g.unlockedSlots=d.unlockedSlots;g.slots=d.slots.map(a=>a?{protons:a.protons,uuid:AtomicRules.safeUuid()}:null);s.revision=d.revision;const elapsed=Math.max(0,Math.min((Date.now()-d.savedAt)/1000,(1+(m.offlineHoursLevel||0))*3600));if(elapsed>1){const mass=g.slots.filter(Boolean).reduce((sum,a)=>sum+(Number(ATOM_REGISTRY[a.protons].mass)||a.protons),0);e.coins+=mass*(e.prestigeLevel+1)*e.detectors.length*.12*elapsed;}m.applyPermanentUpgrades?.();g.renderSlots();g.syncWithAccelerator();s.markDirty();queueMicrotask(()=>window.historyController?.sync(true));}
    SaveManager.SAVE_KEY=KEY;
    SaveManager.hasSave=()=>Boolean(storage.get(KEY)||storage.get(V5)||storage.get(V4)||storage.get(V3)||storage.get(LEGACY));
    SaveManager.save=()=>{const s=window.atomicSession;if(!s||s.destroyed||SaveManager.isResetting)return false;const p=payload(),v=AtomicRules.validateSave(p,ATOM_REGISTRY);if(!v.ok){console.error('[Atomic Idle][save]',v.error);return false;}return storage.set(KEY,JSON.stringify(p));};
    SaveManager.load=()=>{let raw=storage.get(KEY),migration='';if(!raw){raw=storage.get(V5);if(raw)migration='previous';}if(!raw){raw=storage.get(V4);if(raw)migration='previous';}if(!raw){raw=storage.get(V3);if(raw)migration='previous';}if(!raw){raw=storage.get(LEGACY);if(raw)migration='legacy';}if(!raw)return false;let d;try{d=JSON.parse(raw);if(migration==='previous')d=AtomicRules.migratePreviousSave(d);if(migration==='legacy')d=AtomicRules.migratePreviousSave(migrateLegacy(d));if(d&&d.historyUnlockedIds.length===0&&d.prestigeLevel>0)d.historyUnlockedIds=(globalThis.HISTORY_FRAGMENTS||[]).slice(0,d.prestigeLevel).map(fragment=>fragment.id);}catch(e){storage.set(BACKUP,raw);console.error('[Atomic Idle][save parse]',e);return false;}const v=AtomicRules.validateSave(d,ATOM_REGISTRY);if(!v.ok){storage.set(BACKUP,raw);console.error('[Atomic Idle][save validation]',v.error);return false;}apply(d);if(migration)SaveManager.save();return true;};
    SaveManager.resetAll=()=>{if(!confirm('Reiniciar todo o progresso? Esta ação não pode ser desfeita.'))return;SaveManager.isResetting=true;storage.remove(KEY);storage.remove(V5);storage.remove(V4);storage.remove(V3);storage.remove(LEGACY);storage.remove('particle_idle_player_name');storage.remove('atomic_idle_tutorial_completed');location.reload();};

    const oldFusion=MissionManager.prototype.recordFusion;
    MissionManager.prototype.recordFusion=function(resultZ,leftZ,rightZ,triggerElement){if(Number.isInteger(leftZ)&&Number.isInteger(rightZ)){const key=AtomicRules.reactionKey(leftZ,rightZ,resultZ);this.reactionCounts[key]=(this.reactionCounts[key]||0)+1;this.synthesizedElements.add(resultZ);this.roundCounters.fusions++;window.discoveryController?.discover(resultZ,triggerElement,'fusion');}oldFusion?.call(this,resultZ);window.atomicSession?.onProgress('fusion');};
    const oldDetection=MissionManager.prototype.recordDetection;
    MissionManager.prototype.recordDetection=function(atom,earned){this.roundCounters.detections++;this.roundCounters.detectedCoins+=Math.max(0,Number(earned)||0);oldDetection?.call(this,atom,earned);window.atomicSession?.onProgress('detection');};
    MissionManager.prototype.recordSlotPurchase=function(){this.roundCounters.slotsBought++;window.atomicSession?.onProgress('slot_purchase');};
    MissionManager.prototype.hasReaction=function(a,b,r){return (this.reactionCounts[AtomicRules.reactionKey(a,b,r)]||0)>0;};
    MissionManager.prototype.getMaxAllowedInjectorZ=function(){const accelerator=AtomicRules.ACCELERATOR_MAX_Z[Math.max(1,Math.min(14,this.fusionLevel))],joint=Math.min(this.postIronModules?.cryo||0,this.postIronModules?.toroidal||0),postMax=joint?AtomicRules.TIER_RANGES[joint][1]:26,levelMax=Math.floor(1+(this.playerLevel-1)*2.4);return Math.min(118,accelerator,postMax,Math.max(1,levelMax));};
    MissionManager.prototype.initNextBounty=function(){const maxZ=this.getMaxAllowedInjectorZ?.()||2,available=this.secondaryPool.filter(x=>x.type!=='heavy_fusion'||maxZ>=26),p=window.gameEngine?.prestigeLevel||0,pick=available[Math.floor(Math.random()*available.length)];this.activeBounty={...pick,target:AtomicRules.replacementTarget(pick.target,p,1e7),claimId:AtomicRules.safeUuid()};this.bountyProgress=0;this.updateBountyProgressHUD?.();};
    const oldBountyCheck=MissionManager.prototype.checkBountyCompletion;
    MissionManager.prototype.checkBountyCompletion=function(){if(this.bountyClaiming)return;this.bountyClaiming=true;try{return oldBountyCheck.call(this);}finally{this.bountyClaiming=false;}};
    MissionManager.prototype.createDynamicSubstitute=function(){if(this.currentMissionIndex>=49)return;const p=window.gameEngine?.prestigeLevel||0,choices=[['fusions',AtomicRules.replacementTarget(5+this.playerLevel,p,500)],['hits',AtomicRules.replacementTarget(20+this.playerLevel*3,p,100000)],['coins',AtomicRules.replacementTarget(400*Math.pow(1.12,this.playerLevel),p,1e9)]],pick=choices[this.currentMissionIndex%choices.length],[type,target]=pick;const labels={fusions:`Pesquisa contínua: realize ${target} novas sínteses`,hits:`Calibração: registre ${target} passagens no detector`,coins:`Detecção: ganhe ${formatQuantumNumber(target)} moedas`};this.dynamicSubstitute={type,target,current:0,pt:labels[type],en:labels[type]};this.replacementMission={...this.dynamicSubstitute};this.missionState='replacement_active';};
    const oldComplete=MissionManager.prototype.completeCurrentMission;
    MissionManager.prototype.completeCurrentMission=function(){if(this.missionState==='completed')return;this.missionState='completed';oldComplete.call(this);if(this.currentMissionIndex===49)this.prestigeCalibrationStart=this.roundCounters.fusions;this.replacementMission=this.dynamicSubstitute?{...this.dynamicSubstitute}:null;this.missionState=this.playerLevel>=50?'prestige_ready':this.dynamicSubstitute?'replacement_active':'active';};
    MissionManager.prototype.triggerPrestigeAscension=function(){if(this.playerLevel<50||this.missionState!=='prestige_ready'||!window.gameEngine||!window.fusionGrid)return;const modules={...this.postIronModules};window.gameEngine.prestigeLevel++;const p=window.gameEngine.prestigeLevel;this.playerLevel=1;this.currentMissionIndex=0;this.currentInjectorZ=1;this.fusionLevel=1;this.atomPurchases=this.injectorUpgrades=this.speedPurchases=this.detectorPurchases=this.protonPurchases=0;this.maxProtonsSynthesized=1;this.totalFusions=this.totalDetections=this.totalSold=0;this.dynamicSubstitute=this.replacementMission=null;this.missionState='active';this.roundCounters={detections:0,fusions:0,detectedCoins:0,slotsBought:0,modulesBought:0};this.reactionCounts={};this.synthesizedElements=new Set();this.postIronModules=modules;window.gameEngine.coins=50*(p+1);window.gameEngine.speedBonus=0;window.gameEngine.detectors=[{angle:0,pulseTimer:0,label:'DET-01'}];window.fusionGrid.unlockedSlots=4;window.fusionGrid.slots=new Array(8).fill(null);window.fusionGrid.addAtomToSlot(0,1);document.getElementById('modal-system')?.classList.add('hidden');this.showToast(`ASCENSÃO CONCLUÍDA! Nível LV ${p}. Módulos permanentes preservados.`);window.atomicSession?.markDirty();SaveManager.save();};

    class AtomicSession{
        constructor(engine,grid,missions){this.engine=engine;this.grid=grid;this.missions=missions;this.revision=0;this.destroyed=false;this.abort=new AbortController();this.saveInterval=null;this.lastSavedRevision=0;missions.postIronModules={cryo:0,toroidal:0};missions.roundCounters={detections:0,fusions:0,detectedCoins:0,slotsBought:0,modulesBought:0};missions.synthesizedElements=new Set();missions.discoveredElementsLifetime=new Set([1]);missions.hydrogenCardPresented=false;missions.historyUnlockedIds=new Set();missions.historySeenIds=new Set();missions.pendingHistoryFragmentId=null;missions.reactionCounts={};missions.missionState='active';missions.replacementMission=null;grid.session=this;this.installControls();this.saveInterval=setInterval(()=>SaveManager.save(),15000);window.addEventListener('storage',e=>this.onStorage(e),{signal:this.abort.signal});window.addEventListener('beforeunload',()=>SaveManager.save(),{signal:this.abort.signal});}
        markDirty(){this.engine.markUiDirty();}
        renderUi(){this.missions.updateHUD?.();this.missions.updateMissionProgressBar?.();this.missions.updateUpgradesUI?.();this.missions.updateShopUI?.();this.grid.updateSlotPurchaseUI();this.updateModuleUi();window.periodicTableController?.syncButton();window.historyController?.sync(false);}
        onProgress(){this.missions.checkMissions?.();this.markDirty();}
        buyModule(kind){const m=this.missions,level=m.postIronModules[kind],next=level+1,cost=AtomicRules.moduleCost(next,this.engine.prestigeLevel);if(next>10)return;if(!AtomicRules.canBuyModule(next,m.postIronModules,m.fusionLevel)){this.grid.announce(`Tier ${next} requer acelerador N${AtomicRules.TIER_ACCELERATOR[next]} e o outro módulo no Tier ${Math.max(0,next-1)}.`);return;}if(this.engine.coins<cost){this.grid.announce(`Recursos insuficientes: ${cost} moedas.`);return;}this.engine.coins-=cost;m.postIronModules[kind]=next;m.roundCounters.modulesBought++;this.grid.announce(`${kind==='cryo'?'Criogenia supercondutora':'Confinamento toroidal'} no Tier ${next}.`);this.onProgress('module_purchase');SaveManager.save();}
        /** Explica o bloqueio pós-ferro em vez de depender apenas da cor. */
        updateModuleUi(){
            for(const kind of ['cryo','toroidal']){
                const level=this.missions.postIronModules[kind],next=level+1;
                const other=kind==='cryo'?'toroidal':'cryo';
                // A finalidade permanece visível mesmo quando o restante do texto muda de estado.
                const purpose=kind==='cryo'?'Estabiliza sínteses além do ferro':'Mantém núcleos pesados no anel';
                const button=document.getElementById(`btn-module-${kind}`),description=document.getElementById(`desc-module-${kind}`);
                if(!button||!description)continue;
                if(level>=10){description.textContent=`${purpose} · todas as sínteses até Z=118 liberadas`;button.textContent='MÁX';button.disabled=true;continue;}
                const requiredAurora=AtomicRules.TIER_ACCELERATOR[next];
                const range=AtomicRules.TIER_RANGES[next];
                description.textContent=`${purpose} · Tier ${level}/10 · próximo libera Z=${range[0]}–${range[1]}`;
                if(this.missions.fusionLevel<requiredAurora){
                    const tierData=this.missions.fusionTiers?.find(tier=>tier.level===requiredAurora);
                    button.textContent=`BLOQ. AURORA N${requiredAurora}`;
                    button.title=`Requer AURORA N${requiredAurora}${tierData?` (disponível no LV ${tierData.reqPlayerLv})`:''}.`;
                    button.disabled=true;
                }else if(next>1&&(this.missions.postIronModules[other]||0)<next-1){
                    button.textContent=`BLOQ. OUTRO T${next-1}`;
                    button.title=`Eleve o outro módulo ao Tier ${next-1}.`;
                    button.disabled=true;
                }else{
                    const cost=AtomicRules.moduleCost(next,this.engine.prestigeLevel);
                    button.textContent=typeof formatQuantumNumber==='function'?formatQuantumNumber(cost):String(cost);
                    button.title=`Comprar Tier ${next}; libera Z=${range[0]}–${range[1]} quando os dois módulos alcançarem este Tier.`;
                    button.disabled=this.engine.coins<cost;
                }
            }
        }
        installControls(){const o={signal:this.abort.signal};document.getElementById('btn-buy-slot')?.addEventListener('click',()=>this.grid.buyNextSlot(),o);for(const k of ['cryo','toroidal'])document.getElementById(`btn-module-${k}`)?.addEventListener('click',()=>this.buyModule(k),o);this.installDialog(o);}
        installDialog(o){const modal=document.getElementById('modal-system'),open=document.getElementById('btn-open-config'),close=document.getElementById('btn-close-modal');if(!modal||!open||!close)return;let returnFocus=null;const hide=()=>{modal.classList.add('hidden');document.querySelectorAll('#screen-hud button,#screen-hud select').forEach(x=>x.removeAttribute('inert'));returnFocus?.focus();};open.addEventListener('click',()=>{returnFocus=open;setTimeout(()=>close.focus(),0);},o);close.addEventListener('click',hide,o);modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();hide();}if(e.key==='Tab'){const f=[...modal.querySelectorAll('button:not(:disabled),select,input')];if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}},o);}
        onStorage(e){if(e.key!==KEY||!e.newValue)return;try{const d=JSON.parse(e.newValue);if(d.revision>this.revision){const n=document.getElementById('storage-warning');if(n){n.textContent='Progresso mais recente detectado em outra aba. Recarregue para continuar sem sobrescrevê-lo.';n.classList.remove('hidden');}this.destroyed=true;}}catch(err){console.warn('[Atomic Idle][storage event]',err);}}
        destroy(){if(this.destroyed&& !this.saveInterval)return;SaveManager.save();this.destroyed=true;clearInterval(this.saveInterval);this.saveInterval=null;this.abort.abort();window.periodicTableController?.destroy();window.discoveryController?.destroy();window.tutorialManager?.destroy();window.historyController?.destroy();this.grid.destroy();this.engine.destroy();}
    }
    window.ensureAtomicSession=()=>{if(window.atomicSession)return window.atomicSession;if(!window.gameEngine||!window.fusionGrid||!window.missionManager)return null;if(window.atomicLegacySaveInterval){clearInterval(window.atomicLegacySaveInterval);window.atomicLegacySaveInterval=null;}if(window.atomicLegacyBeforeUnload)window.removeEventListener('beforeunload',window.atomicLegacyBeforeUnload);window.atomicSession=new AtomicSession(window.gameEngine,window.fusionGrid,window.missionManager);return window.atomicSession;};
    window.AtomicStorage=storage;window.AtomicSession=AtomicSession;
})();
