'use strict';
const assert=require('node:assert/strict');
const R=require('../js/rules.js');
const registry=Object.fromEntries(Array.from({length:118},(_,i)=>[i+1,{protons:i+1}]));
const base=()=>({saveVersion:6,revision:1,savedAt:Date.now(),coins:10,photons:0,prestigeLevel:0,playerLevel:1,currentMissionIndex:0,fusionLevel:1,unlockedSlots:4,slots:Array(8).fill(null),modules:{cryo:0,toroidal:0},round:{detections:0,fusions:0,detectedCoins:0,slotsBought:0,modulesBought:0},synthesizedZ:[],discoveredZLifetime:[1],hydrogenCardPresented:false,historyUnlockedIds:[],historySeenIds:[],pendingHistoryFragmentId:null,reactionCounts:{},missionState:'active',replacementMission:null,speedBonus:0,detectorsCount:1,currentInjectorZ:1,buffExpiresAt:{collider:0,cryo:0,condenser:0},offlineHoursLevel:0,quantumLuckLevel:0});
assert.equal(R.MAX_SLOTS,8);assert.equal(R.unlockedForLevel(1),4);assert.deepEqual([2,3,4,5].map(R.unlockedForLevel),[5,6,7,8]);
for(let l=1;l<20;l++)assert.ok(R.unlockedForLevel(l)<=8);
assert.ok(R.slotCost(6)>R.slotCost(5));assert.ok(R.slotCost(5,2)>R.slotCost(5,0));
assert.equal(R.protonCost(0,0),60);assert.equal(R.protonCost(1000,0),30000);assert.ok(R.protonCost(1000,1)>30000);assert.ok(R.protonCost(1000,2)>R.protonCost(1000,1));
assert.equal(R.reactionKey(2,1,3),R.reactionKey(1,2,3));assert.equal(R.canSynthesize(1,1,{acceleratorLevel:1}).resultZ,2);
assert.equal(R.isNewDiscovery(2,new Set([1]),'fusion'),true);assert.equal(R.isNewDiscovery(2,new Set([1]),'purchase'),false);assert.equal(R.isNewDiscovery(2,new Set([1,2]),'fusion'),false);
const v3={...base(),saveVersion:3,synthesizedZ:[2,3,3]};delete v3.discoveredZLifetime;delete v3.hydrogenCardPresented;const migrated=R.migratePreviousSave(v3);assert.equal(migrated.saveVersion,6);assert.deepEqual(migrated.discoveredZLifetime,[1,2,3]);assert.equal(migrated.hydrogenCardPresented,false);assert.deepEqual(migrated.historyUnlockedIds,[]);
const v4={...base(),saveVersion:4,discoveredZLifetime:[1,2,6]};delete v4.hydrogenCardPresented;assert.deepEqual(R.migratePreviousSave(v4).discoveredZLifetime,[1,2,6]);
assert.equal(R.canSynthesize(13,13,{acceleratorLevel:4}).ok,true);assert.equal(R.canSynthesize(13,13,{acceleratorLevel:3}).ok,false);
assert.equal(R.canSynthesize(1,26,{acceleratorLevel:5,cryoLevel:1,toroidalLevel:0}).ok,false);
assert.equal(R.canSynthesize(1,26,{acceleratorLevel:5,cryoLevel:1,toroidalLevel:1}).ok,true);
assert.equal(R.canBuyModule(2,{cryo:1,toroidal:0},6),false);assert.equal(R.canBuyModule(2,{cryo:1,toroidal:1},5),false);assert.equal(R.canBuyModule(2,{cryo:1,toroidal:1},6),true);
assert.equal(R.replacementTarget(100,2),Math.ceil(100*Math.pow(1.18,2)));
const boosted=R.effectiveSpeed(2,.2,true,.97),normal=R.effectiveSpeed(2,.2,false,.97);assert.ok(boosted>normal);assert.equal(normal,2*1.2*.97);
const baseIncome=R.incomePerSecond({particleYield:10,angularSpeed:Math.PI*2,detectors:2});assert.equal(baseIncome,20);assert.equal(R.incomePerSecond({particleYield:10,angularSpeed:Math.PI*2,detectors:2,collider:true}),25);assert.equal(R.incomePerSecond({particleYield:10,angularSpeed:Math.PI*2,detectors:2,collider:true,condenser:true}),37.5);
let warned=false;const blocked=R.createSafeStorage({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');},removeItem(){throw Error('blocked');}},()=>warned=true);assert.equal(blocked.get('x'),null);assert.equal(blocked.set('x','y'),false);assert.equal(blocked.remove('x'),false);assert.equal(blocked.available,false);assert.equal(warned,true);
assert.equal(R.validateSave(base(),registry).ok,true);
for(const bad of [null,{},'{corrupt'])if(typeof bad==='object')assert.equal(R.validateSave(bad,registry).ok,false);
let b=base();b.slots.pop();assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.slots[4]={protons:1};assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.slots[0]={protons:119};assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.unlockedSlots=5;assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.modules.cryo=1;assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.discoveredZLifetime=[];assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.discoveredZLifetime=[1,2,2];assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.discoveredZLifetime=[1,119];assert.equal(R.validateSave(b,registry).ok,false);
b=base();delete b.hydrogenCardPresented;assert.equal(R.validateSave(b,registry).ok,false);
b=base();delete b.historyUnlockedIds;assert.equal(R.validateSave(b,registry).ok,false);
b=base();b.pendingHistoryFragmentId=42;assert.equal(R.validateSave(b,registry).ok,false);
console.log('AtomicRules: regras, save, armazenamento bloqueado e expiração de buff verificados.');
