'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));
assert.equal(ids.size,[...html.matchAll(/\bid="([^"]+)"/g)].length,'IDs HTML duplicados');
for(const f of ['engine.js','fusion.js','missions.js','intro.js','hardening.js','tutorial.js']){const src=fs.readFileSync(path.join(root,'js',f),'utf8');for(const m of src.matchAll(/getElementById\(['"]([^'"]+)['"]\)/g))assert.ok(ids.has(m[1]),`${f}: #${m[1]} ausente`);}
assert.match(html,/id="fusion-slots-container"/);assert.doesNotMatch(html,/id="btn-manual-pulse"/);assert.match(html,/id="accelerator-canvas" role="button" tabindex="0"/);assert.match(html,/role="dialog"/);assert.match(html,/aria-live="polite"/);
const engine=fs.readFileSync(path.join(root,'js','engine.js'),'utf8'),fusion=fs.readFileSync(path.join(root,'js','fusion.js'),'utf8'),hardening=fs.readFileSync(path.join(root,'js','hardening.js'),'utf8');assert.match(engine,/cancelAnimationFrame\(this\.rafId\)/);assert.match(engine,/this\.abortController\.abort\(\)/);assert.match(fusion,/this\.abortController\.abort\(\)/);assert.match(hardening,/clearInterval\(this\.saveInterval\)/);assert.match(fusion,/touchcancel/);
assert.match(html,/COMBINAÇÕES ATÔMICAS IDLE/);assert.match(html,/id="tutorial-overlay"[^>]+role="dialog"[^>]+aria-modal="true"/);assert.match(html,/id="btn-open-tutorial"/);assert.match(html,/imagens\/personagens\/01_aris_thorne\.jpg/);assert.match(html,/id="discovery-overlay"[^>]+role="dialog"[^>]+aria-modal="true"/);assert.match(html,/id="history-overlay"/);assert.match(html,/id="global-project-footer"/);
const characters=fs.readFileSync(path.join(root,'js','characters.js'),'utf8'),tutorial=fs.readFileSync(path.join(root,'js','tutorial.js'),'utf8'),intro=fs.readFileSync(path.join(root,'js','intro.js'),'utf8');
for(let n=1;n<=10;n++){const code=String(n).padStart(2,'0');assert.match(characters,new RegExp(`'${code}'\\s*:`),`Personagem ${code} ausente do registro`);assert.ok(fs.existsSync(path.join(root,'dados','dados_personagens',`${code}_descricao.md`)),`Perfil ${code} ausente`);}
assert.match(tutorial,/atomic_idle_tutorial_completed/);assert.match(tutorial,/this\.hud\.inert = true/);assert.match(tutorial,/this\.hud\.inert = false/);assert.match(tutorial,/this\.abortController\.abort\(\)/);assert.match(tutorial,/steps = \[/);assert.match(intro,/tutorialManager\?\.maybeStart\(\)/);
const allSource=[html,...fs.readdirSync(path.join(root,'js')).filter(f=>f.endsWith('.js')).map(f=>fs.readFileSync(path.join(root,'js',f),'utf8')),...fs.readdirSync(path.join(root,'css')).map(f=>fs.readFileSync(path.join(root,'css',f),'utf8'))].join('\n');
assert.doesNotMatch(allSource,/(?:^|["'`(])(?:\.\.\/)?img\//m,'Referência ativa à antiga pasta img');assert.doesNotMatch(allSource,/atomos_hd_256x256/,'Referência ao diretório atômico antigo');
const atomImageDir=path.join(root,'imagens','atomos'),atomDataDir=path.join(root,'dados','dados_elementos'),pngs=fs.readdirSync(atomImageDir).filter(f=>f.endsWith('.png')),mds=fs.readdirSync(atomDataDir).filter(f=>f.endsWith('.md'));assert.equal(pngs.length,118);assert.equal(mds.length,118);
for(const file of mds){const profile=fs.readFileSync(path.join(atomDataDir,file),'utf8');assert.match(profile,/\| Família \/ bloco \|/i,`${file}: família/bloco ausente`);}
const atomSource=fs.readFileSync(path.join(root,'js','atoms.js'),'utf8');for(const match of atomSource.matchAll(/\{ z: (\d+), s: "([^"]+)", m: [^,]+, n_pt: "[^"]+", n_clean: "([^"]+)"/g)){assert.ok(fs.existsSync(path.join(atomImageDir,`${match[1]}_${match[3]}.png`)),`Imagem ausente para Z=${match[1]}`);}
const discovery=fs.readFileSync(path.join(root,'js','discovery.js'),'utf8'),encyclopedia=fs.readFileSync(path.join(root,'js','element-encyclopedia.js'),'utf8');assert.match(discovery,/discoveredElementsLifetime/);assert.match(discovery,/SaveManager\.save\(\)/);assert.match(discovery,/this\.queue\.push/);assert.match(discovery,/this\.abortController\.abort\(\)/);assert.match(encyclopedia,/presenterFor/);
assert.match(discovery,/maybePresentHydrogen/);assert.match(discovery,/hydrogenCardPresented/);assert.match(discovery,/atomic-tutorial-complete/);assert.match(tutorial,/atomic-tutorial-complete/);assert.match(fusion,/REQUER NÍVEL/);assert.match(fusion,/slot-level-locked/);
const prestigeBody=(hardening.match(/triggerPrestigeAscension=function\(\)[\s\S]*?class AtomicSession/)||[])[0]||'';assert.doesNotMatch(prestigeBody,/hydrogenCardPresented\s*=/,'Prestígio não deve reiniciar a ficha do hidrogênio');
const generated=fs.readFileSync(path.join(root,'js','element-profiles.generated.js'),'utf8');assert.match(generated,/ELEMENT_PROFILE_MARKDOWN/);assert.equal((generated.match(/"\d+":"# /g)||[]).length,118,'Perfis embarcados incompletos');
const historyGenerated=fs.readFileSync(path.join(root,'js','history-fragments.generated.js'),'utf8');assert.match(historyGenerated,/HISTORY_FRAGMENTS/);assert.equal((historyGenerated.match(/"id":/g)||[]).length,13,'Fragmentos históricos embarcados incompletos');
for(const documentName of ['RELEASE.md','DECLARACAO.md','PRIVACIDADE.md'])assert.ok(fs.existsSync(path.join(root,documentName)),`${documentName} ausente`);
assert.ok(fs.existsSync(path.join(root,'imagens','telas_fundo','tela_fundo_linha_tempo.jpg')),'Fundo da linha do tempo ausente');
const gameCss=fs.readFileSync(path.join(root,'css','game.css'),'utf8');assert.match(gameCss,/tela_fundo_linha_tempo\.jpg/);assert.match(gameCss,/#game-container\{height:auto!important/);assert.match(gameCss,/\.panel-upgrades\{display:flex!important/);assert.match(gameCss,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)!important/);
console.log(`HTML/JS: ${ids.size} IDs únicos e referências estáticas válidas.`);
